version: '3'

services:
  bai_mysqldb:
      build: ./build/mysql
      container_name: bai_db
      restart: always
      env_file:
          - ./.env.local
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ROOT_USER}
          - MYSQL_RANDOM_ROOT_PASSWORD=""
      volumes:
          - ./build/mysql/data/:/var/lib/mysql
      ports:
          - "3307:3306"
      expose:
          - "3307"
      command: --default-authentication-plugin=mysql_native_password
      networks:
          - overlay
  bai_nginx:
      build: ./build/nginx
      container_name: bai_server
      restart: always
      ports:
          - "8000:80" # Web
      volumes:
          - ./build/nginx/logs/:/var/log/nginx
          - ./app/website:/var/www/html
      networks:
          - overlay
  bai_phpfpm:
      build: ./build/phpfpm
      container_name: php
      hostname: bai_phpfpm
      restart: always
      volumes:
          - ./app/website:/var/www/html
      ports:
        - 9000:9000
      networks:
          - overlay
networks:
  overlay:
