version: '3'

services:
  bai_mysqldb:
      build: ./build/mysql
      container_name: bai_db
      restart: always
      env_file:
          - ./.env.local
      environment:
          - MARIADB_ROOT_PASSWORD=root
          - MARIADB_DATABASE=bai
          - MARIADB_USER=root
        #   - MARIADB_MYSQL_LOCALHOST_USER=root
      volumes:
          - ./build/mysql/data/:/var/lib/mysql
      ports:
          - "3308:3306"
      expose:
          - "3308"
      command: --default-authentication-plugin=mysql_native_password
      networks:
          - overlay
  bai_phpmyadmin:
      build: ./build/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - UPLOAD_LIMIT=21722226000
      networks:
        - overlay
  bai_nginx:
      build: ./build/nginx
      container_name: bai_server
      restart: always
      ports:
          - 80:80 # Web
      volumes:
          - ./build/nginx/logs/:/var/log/nginx
          - ./app/website:/var/www/html
      networks:
          - overlay
  bai_phpfpm:
      build: ./build/phpfpm
      container_name: php
      hostname: bai_phpfpm
      privileged: true
    #   restart: always
      volumes:
          - ./app/website:/var/www/html
          - ./build/phpfpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/opcache.ini
      ports:
        - 9000:9000
    #   command: bash -c "composer update --ignore-platform-reqs"
      networks:
          - overlay
networks:
  overlay:
 