name: Webform Config Ignore
type: module
description: Ignores configuration imports and export of existing Webforms.
core_version_requirement: ^8 || ^9
dependencies:
  - config_filter:config_filter

# Information added by Drupal.org packaging script on 2021-03-14
version: '8.x-1.2'
project: 'webform_config_ignore'
datestamp: 1615703764
